### ISSUE TITLE
fetchPolicy="network-only" still returns data from the cache

### ISSUE THREAD

**Issue by bradleyayers** [trojanowski/react-apollo-hooks#81]
It seems like even when I'm using `network-only` that data from the cache is being returned immediately. I would have expected that the rendering phases would be:

```ts
{ data: {},           loading: true }  // render 1
{ data: { foo: {…} }, loading: false } // render 2
// done
```

**Edit:** On further debugging I'm not able to reproduce this, closing for now.

**Comment by trojanowski** [comment]
@bradleyayers it seems it's an issue with apollo-client which is already fixed in master:

* https://github.com/apollographql/apollo-client/pull/4352
* https://github.com/apollographql/react-apollo/issues/556

**Comment by trojanowski** [comment]
Apollo Client 2.5.0 is already released. @bradleyayers could you please confirm if it solved the problem for you?

**Comment by wrod7** [comment]
still happening on the latest client. 2.5.2, definitely an issue with apollo-client

**Comment by ziedHamdi** [comment]
Who found a workaround for this?

**Comment by adrianescat** [comment]
I need a solution for this too. `fetchPolicy: "network-only"` is not working.
